### ISSUE TITLE
zhihu_话题分类的字典载入

### ISSUE THREAD

**Issue by lyuchuny3** [Qinbf/Tensorflow#1]
你好，我尝试用你的代码训练，得到了一个model
但是在 zhihu_eval.py 中的45行，
vocab_processor = tf.contrib.learn.preprocessing.VocabularyProcessor.restore("vocab_dict")
按照我的理解，这个字典应该是训练模型得到的权重， 但在训练的过程并没有保存"vocab_dict"
请问 “"vocab_dict"是从哪里来的
谢谢解答

**Comment by Qinbf** [comment]
@lyuchuny3 
在cnn.py的代码中应该要保存vocab_dict，我可能是误删掉了。
加上：
vocab_processor.save("vocab_dict")
我刚刚更新代码了
