### ISSUE TITLE
换了数据集运行cnn文件出现错误

### ISSUE THREAD

**Issue by yifanjiang19** [Qinbf/Tensorflow#2]
按照代码中数据集被分成10个部分，用data_topic_block_0.txt进行训练，我换成data_topic_block_1.txt之后就出现错误：
File "cnn.py", line 101,in <module>
    max_document_length = max([len(x.split(",") for x in x_text])
AttributeError: 'float' object has no attribute 'split'
请问这是什么原因？

**Comment by Qinbf** [comment]
@yueruchen 你把出错的行打印出来看一下，有可能文件中有空行。

**Comment by bluekingdom** [comment]
@yueruchen block_1中有两行不是str类型的，可以通过type(x) != str 来滤除。

**Comment by yifanjiang19** [comment]
已经解决，把不含'w'的行删除即可
